name = "gemini-quiz-api"
main = "https://gemini-quiz-api.buhle-1ce.workers.dev"  # <--- CHANGE THIS from quiz.js to api.js
compatibility_date = "2024-04-01"

[[d1_databases]]
binding = "QUIZ_DB"
database_name = "quiz"
database_id = "968a34a2-480e-4e7d-87a5-20bd1bf400df"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "ai-files"